language: ruby
rvm:
  - 2.4
  - 2.6
sudo: false
cache: bundler
before_script: bundle update
script: script/cibuild
notifications:
  email:
    recipients:
      - mercenary@jekyllrb.com
    on_success: change
    on_failure: change
